version: '3'

services:
  product-catalog-service:
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "9081:9081"
    depends_on:
      - redis-cache
      - postgres-db
    environment:
      JAVA_OPTS: -server -Xms32m -Xmx128m -Xss256K -Dsun.net.inetaddr.ttl=60
      DB_HOST: postgres-db
      DB_PORT: 5432
      DB_USER: product-catalog-root
      DB_PASSWORD: cXbGqdMQ4/jy2
      DB_NAME: product-catalog
      REDIS_HOST: redis-cache
      PROFILE: development
    healthcheck:
      test: ["CMD", "curl", "-f", "http://product-catalog-service:9081/actuator/health"]
      interval: 10s
      timeout: 10s
      retries: 5
    restart: on-failure

  postgres-db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: product-catalog-root
      POSTGRES_PASSWORD: cXbGqdMQ4/jy2
      POSTGRES_DB: product-catalog

  redis-cache:
    image: "bitnami/redis:latest"
    ports:
      - "6379:6379"
    environment:
      - DISABLE_COMMANDS=FLUSHDB,FLUSHALL,CONFIG
      - ALLOW_EMPTY_PASSWORD=yes