server:
  port: 9081

spring:
  datasource:
    url: "jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}"
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  flyway:
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
  jpa:
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false # this one will prevent WARN stacktrace for Spring Boot 2 app using PostgresQL
    open-in-view: false
  cache:
    type: redis
    redis:
      time-to-live: PT1H
  redis:
    host: ${REDIS_HOST}