create table PRODUCTS
(
  ID           SERIAL PRIMARY KEY,
  MANUFACTURER VARCHAR(32) NOT NULL,
  NAME         VARCHAR(64) NOT NULL,
  PRICE        DECIMAL     NOT NULL,
  CURRENCY     VARCHAR(8)  NOT NULL
);
